stages:
  - seal

seal-secret:
  stage: seal
  image: alpine:latest
  tags:
    - kube

  before_script:
    # tools 
    - apk add --no-cache curl git bash jq

    # kubeseal
    - KUBESEAL_VERSION=v0.34.0
    - curl -L -o kubeseal.tar.gz https://github.com/bitnami-labs/sealed-secrets/releases/download/${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION#v}-linux-amd64.tar.gz
    - tar -xzf kubeseal.tar.gz
    - chmod +x kubeseal
    - mv kubeseal /usr/local/bin/kubeseal


    # prepare file cert
    - echo "$SEALED_SECRET_CERT_B64" | base64 -d > pub-cert.pem

  script:
    - mkdir -p chart
    - mkdir -p chart/templates
    - |
      echo "Processing secrets-config.json..."
      COUNT=$(jq length secrets-config.json)

      for i in $(seq 0 $((COUNT - 1))); do
        NAME=$(jq -r ".[$i].name" secrets-config.json)
        NAMESPACE=$(jq -r ".[$i].namespace" secrets-config.json)

        echo "Generating secret: $NAME"

        echo "apiVersion: v1" > secret.yaml
        echo "kind: Secret" >> secret.yaml
        echo "metadata:" >> secret.yaml
        echo "  name: $NAME" >> secret.yaml
        # echo "  namespace: $NAMESPACE" >> secret.yaml
        echo "  annotations:" >> secret.yaml
        echo "    'argocd.argoproj.io/sync-wave': '0'" >> secret.yaml
        DOCKERCONFIG_EXISTS=$(jq -r ".[${i}].data | has(\".dockerconfigjson\")" secrets-config.json)
        if [ "$DOCKERCONFIG_EXISTS" = "true" ]; then
          echo "type: kubernetes.io/dockerconfigjson" >> secret.yaml
        else
          echo "type: Opaque" >> secret.yaml
        fi
        echo "stringData:" >> secret.yaml

        KEYS=$(jq -r ".[$i].data | keys[]" secrets-config.json)
        for KEY in $KEYS; do
          VALUE_JSON=$(jq -c ".[$i].data[\"$KEY\"]" secrets-config.json)

          # Jeśli prosty string → traktujemy jako zmienną środowiskową
          if [[ "$VALUE_JSON" =~ ^\"[A-Z0-9_]+\"$ ]]; then
            VAR_NAME=$(echo "$VALUE_JSON" | tr -d '"')
            ENV_VAL=$(printenv "$VAR_NAME")
            if [ -z "$ENV_VAL" ]; then
              echo "ERROR: CI variable $VAR_NAME not set!"
              exit 1
            fi
            VALUE="$ENV_VAL"
          else
            # Jeśli JSON object → podmiana wszystkich nazw zmiennych w środku na wartości z env 
            VALUE=$(echo "$VALUE_JSON" | jq 'walk(if type=="string" and test("^[A-Z0-9_]+$") then env[.] else . end)')
          fi

          echo " $KEY: '$VALUE'" >> secret.yaml
        done

        # Sealing
        kubeseal --cert pub-cert.pem --scope cluster-wide --format yaml < secret.yaml > chart/templates/${NAME}.yaml
      done

    # Git part
    - git config --global user.email "ci@gitlab"
    - git config --global user.name "GitLab CI"
    # - CURRENT_URL=$(git config --get remote.origin.url)
    # - git remote set-url origin "$(echo "$CURRENT_URL" | sed "s#https://#https://gitlab-ci-token:${GITLAB_PAT}@#")"
    # - git remote set-url origin "$(echo "$CURRENT_URL" | sed "s#https://#https://oauth2:${GITLAB_PAT}@#")"
    - git remote set-url origin "https://oauth2:${GITLAB_PAT}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git add chart/templates/
    - git commit -m "Update sealed secrets [ci skip] " || echo "No changes"
    - git push origin HEAD:$CI_COMMIT_REF_NAME

  artifacts:
    paths:
      - chart/templates/

