---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: gitlab-registry-secret
spec:
  encryptedData:
    .dockerconfigjson: AgCd2asybdAgBvb2XN4QZZeXhy98kaml3jJkDvDwYVXq92Tk+hNBYrCOtVp6k4HGBcYoKqJJ/xbn9co+a5zc3a21punp0NrHXi16nX1UKsjLPqEJaEtsdm8he+3CnJYBI+xQSgOFs9X6eVoJthZADqnfbVITaSPbaPdXfTBgBYH3vLcN+vY6W6GiWulqKSEZqDhVjwWsTrxjRgNbRjC8sawOL9oYnMDyEAWmiIbCgXkihIm8zwC7NQWqi7oAgj5ydTJuH77gEykykV2bN/WoZamlc33BQx0PzM22ox+uP3+Ff21ihlbvTkjmHQv2FzLtiG5DflvKGD3iRFzaczjeVGxSrviUmlAG5AUeFOP8WzEMDFZEScQMf82OCH6BV2/1EPCo4nk+ABH1/wKLNLt0p4QuL8bu1dGtK/wtDV+E+nlaJS9djGFjeWop1wseLw88vbazySHsj6RxrWDyosbKyQgyQI29yHYY7DdgnWUnM/5tFNuG6z4CrgpSOJL7mywjMDkgH43mVS1M2eQswud2+beepPg/ZNVl5zan/DL3G5SoNFn8lUeWZQSIQbomWPZK6Cnu8iXn/SrMn6a6azLgAEOrKsazgCtLShWwI2VeIiIy+B2keVtpiO+r+q4bJzyYxE59LN6hAMBRp/X/tGp6K24mwAv02gq4L8TWtshY5em/msS3XP3KF222raaeNS6ppyaaoIY5J461Q4wsQb+lcRY00cErw86qqyjJfMrHQxOKscNtyToTsqxKMvjArQlq0zz1DfF6zY4f0YiE+XCzEpnFZSMNrahsgGi/A2fMeIvEjiowMmiv5EIUpcXoef3SJ+1ughz/UZVDXsoLrcZ0HB4fMyZ6HGR+AFofoafuMgt0dzWDZtOJzH77n48ODpyChCLFZZkr5EseGxRr1jjEnDyycTUHqiSMVvSXde+dowk3jRBvcKUgQw7NsUmaJ23eGoJqVxRHerJUBd2+NmRy9ISJzPdhCq6s50GyS0PZ4xO9j3uwloB11O8WxdWi/Qs/KH/EEp7Pu+0et19b9LH4NLaGEELIvCkw6PWkV76AYH8e+a6UXCLp17OLoRZld4m3KDNZywM=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: gitlab-registry-secret
    type: kubernetes.io/dockerconfigjson
