---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-dbowner-secret
spec:
  encryptedData:
    dbOwner: AgCdLLEVZwleK/+2pm5pGyyD4WpL0Nl9Yb2oHuZTIgtlvJEz/kFeDEDkP4BDt3lkJRslxAC/M6m970Md2/HKmT1MvbVJPi0ceJWdBbhC0AabNCL/vv/UUGpHHSmkWrXz13Pg0DdZ/44KJCePkCb04YGCF05ApXrJFRJV3aLU/ntfNA3NpRvUwyQb4Ve2YqytfeQfiC191D9K1teAn30hs++6Ve6ua2VlJuv5NVmv88LexMMT4Q1CqCOOJRFTxngWXos21Ol0nixeSqRQA0IdXrdfKNk55RXxCzJ2ZcBUM2pt1vgDaJSM9OR/+PaJlKKIf+1L8cX6LI72p2FrjbpGB/mqhofsLqSsY7mRc0Gf5TrTtTtkAP1riEgT0A2bFVTdSXC5nQOX4xOH7fZZyjahPdw5ztP55rMTDQrrxq3tj07KqLwW3SQ/MeHrN+bVSkZKvyNmlmoRAi+XwQUdHcTZ53I/h3+8r0A2R6Ud8lanqq+DiiKdjoDaQ1N8qXlM73RuduDV26VCpkamOG6cvHlx68HwZk4BZNO5pLZmFbTcPg+qypaMH6cVEE7TAXSjUwqPMjFlzTMgsOwKWMRJlwyGUP0WaYJUBouaLwCl4OE8XV4Xy4NJ3fTyVr91qffamki68GaGpPUFd/RqncOTO36YpYUvh2NvCTBs4W0Q1X+qeyHgBiN4/cuR3Che8HsFCtlRNvZbzCw/VaFARiEiQPuW
    dbOwnerPass: AgCl2Ld3OrADhwDP0oZ+RxH47Y02Ptac8r7uaC9LYFO9EkMMtT2TaM1lm8MckSmOJjb/W07KQRctJ2CxPFgZEmLQnDJFFTnrbp/UMjgVFaAtzZZAfpygAxB6wWLjQuOx8gkn4pxc3Kyy+XBIIwdB6gHbb4NFDQ2nGm6WIxqFx8SsUiXkj9kcBohGulTqRQohmp5D22loGFsZCdEeMsR1S12idJR7X2SE1ES+bCC5q34jngTrfY3y/x47E3xEDq4ScaLXUSp7GuyEClBFMOQhLsz7ciAuEdgA3on6JFXju4KQylM0Uh16gx++ay9OrvN4AcHcO2vdui3Xo2Gr9jYtu+Td90tBzsfNRJUtVK9gog8KBQLIa/QZJjAvZ8hu3dJfHWhLkB3tSvGMeAMAQXMOLBvNl7pbA8YhkWeB0EM8Mo3CkTLRnoT9DhGoj8RkIcl9w1EIbvWC4W7jH3wFZIyX6p+OTY1l1xOAPigPVPxGtdWIixm2BQ2oYBldJwHSV9JUn5/RigTAvTe0Pc71sss+tie0oOR0SaOBXS10jvSSeQQyn9i+T39FUlXuU56x2sFXqAhZDJtMOThjoR7o9+V+VXAAjFeIeXpZbp9uEeuSw+aEuO2p8CP5aHOQ6lPgXBhyyt/RigoYtUn12FYlw7JgxA1G0SVzn+KG7Fxvo/xKp2DUS68A8BXaGuQb6stSPPIcMFQxzxg/D8vJLOhzg84ImUzNOvqPGhkL4w==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-dbowner-secret
    type: Opaque
