---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-superuser-secret
spec:
  encryptedData:
    dbSuperUser: AgC8Mp1C9mA6nEIjVqf5hFSTd8/3B8E2LnQGn1f+W/AR4J15WuASwz/Mt9z9Qm6pGSUsOU9qvzzDadQzaFHW/KZNZU3PmiZgGdqSQ54KnS0lIdmJFkcvwL14vbSeQ8Rd08XKGoO1jSNleXryo3CcUNQFfWunxdZ83KVer926AFLxCDmUCuL3+Bq6VjxOa71/ASboIAaO7+Ld9ZUlMeiZzabYfQKo6HOFZdidEsZtQooqxi0WGw4o9cUUyr5/gg+j9bnrn49UtQIPCQ6DZtWC6OugcWjQG3BihFNjNoMT5WRA45ZEKE+ucjMl8wPKdZFGrYLModSCnhRjuj1JBy+5+zsYHlVEJ3M4JlYKUfglfYc8e6BgFUjoJ+8eFzCg5t3R1NZ4KUSSdWyaBuOJQRiIL6yg91fCNz1v4sAskiWAYuhUQG7zo/94yZ7aIfcruSXaOQ3a0BryIPSRBPheSRh4BCdNfhTZ+y4ONFri/wdCJLUzgiz2NsxizYhCC8tkugMrTHQoxG967jojDpRVjOfsf0QhTXnaeR3G7hSUWnS6vEICRsFms4U+evQUocQGqyDmmjsihNIC96X0iarsiozqW4iJztQjwSjtG+kuLXU3GDlJibhWyEg5N/by/cfn9PP4izuD9r4Xuu6Ou+BK7HwH003aOyUkF5dJvIYhp12o7FXtmGGqRfiN4SuVF8gxWaCbx2VTd2FV8AmuQg==
    dbSuperUserPass: AgClqv783cKVVoNXkxWylSqL6P2ZesMBUrZZ671Yeur2WrV/ehE7wzvXCtVMf29U4kvp5aSFS3VGDzZqrmESpyv7dGrK3zdM6Ac/erUhYqwhZYtTg8tl1mNLX540bQMvuOhoqSxQQ7YROB/au5eAWwGSKdGnlNfueP+gfDGEzpJ2oYOFKXTAUMRSaE859c63L23ZSjOgLMNC4cLcAP9MqdNMt2bhbFCxw3Np5erRFyixC5trFk9/arEovy4qcMsWOt1j3nBRPQJI8Sal2BRoVqDsePl4knURhV0dHhqc6wE7ZksYyJ4UgDAnFJyfsFyOIOa9jiweP7A1dZJlSawq3ETe366FWU75gEGTHABst1grepd7JOtcgmt06JljLCj6/cN4mZK8F3S5ycbwNg+849xjZxYKTvAsg4c6GWVEd93rFfuAylWRqUy0R2aaeeCbY/W7ayrD9tv4dLrk2IqGQaKtxhnv9qwJAqQtW2qCkQakvxc5FpZC13QgecRzimqHQXyhi7HcFfiCZyfYRrii4fXHPVy9JBhvy7VCkhOSprZRieifp5u88tMSHXIoxXjeHbylzmxZEEwUpfFbZHKyR4fVOHQq7HGYBzJ/lOFn2Cx2xrIe/2IRYw77DKfc4uCWthfNpiWVy2MYBgofwy/+6YidKMAyNxWQBhzJ+aWwiPJrHHGnVRAKCbSFzaIB4qlAgbTvICMNHlsL496zSmmEL1wFIUacFgrKPq9T8b00oNidW/XHvtaVQ+CctGIEFYK2RxT0lGf+omewGY5EypcER0rE
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-superuser-secret
    type: Opaque
