---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: postgres-secret
spec:
  encryptedData:
    dbPass: AgCXm7MB/nI6eaPLyx8E54IlGPkkQe8TVmL34IvqyDWEfkzF/1LVfg7yU/vWd35m7ELcviek0tVqtgEzPHa2l9ngkxep3dPLC/dNgBedy9OB4DwDI4R/OIhW+13STs++q3CHRTcEjk1ZQVcPG7tSd18Dj20JLWRSk+jdywzlO3h31ohlF73dkuaxjQIJPjoDahtUHAnHau325kXtSmIQMr32qHTUW6kdnoGOVy4BlX+UTNOeTlCwDJ2W3bjcWFAicyXCgmEMzcKTQ0eh6tLL/4g+nSMcf+mMiqPolKNr5Lpx8PQ2ZG8Fk1NE5et1/heQ8LGZnj9BHNYXLZAGZgQO0YydhKPWHX/5tIIokhuUB06JGi/OFvLKwgDZOybVYDzX5St+3nbPo3JwXAfDyPudRMOgPSYXOUCuxWdReWywFryOiFy7RthSS8T4dQklQc+iKcA16cCp3hPzsjcnze8/Umu6Mx0AC4fV51Yj1mrld7o9MwofRaEVxUBF5jRqz0gH/YWVUFasxhDewSh4NGCivS+Ppgp8z0MUg1tTL+tuEnxBoyJBU4SMrDR9ewITnRTvz47CPrrADpzYB7BLbVa6v3m5HGlyIwXpYcNS5yUyPcfrasMAZTUnNreRZ3hui85WVHLvnfUoJw24UznpvdyEIT/GvBibp+o4VqMWyQ2/Q8fq0iwOnjXeiwiWFfN3ON12wECKM34IFAPNUvlrWPwe9x/LOeG7
    dbUser: AgBE+AoOuXlD+sV8IPnPokXByJWq2ZmwELz/uINRrRmIl/SPB8NTtdGg4205VH5dGuLu8VFS9O5iACPFy5NtDEr6J23SgOz8RLXt/W7N4nQ1xhbDO+gqj96Tq+ioUtIuWo/x9StjSSxLxwpsGVw5jrCFKlra2inioifxSlaF+p3F5BOUvlDP52wXYonCkk5tQg7iI0dTxeAyzSzTE0yZINg4DPustwygtPXCqdh7fP2qh1wXURA9wooyCUz/+TLOJzQJNmq04NcGoRdQcEyHHjhCzJChyTGt5ArTnhBg44QKfq/73W7nu8e++b9gJ+GvywDG599/beuFGJC+z+fbW5bTQBSPDBI0EEYbJc7f8tMKo7e4c7z3O3uYXIQc1bWVd8fHQJkp0ID0Kn9KxFTdSlJL4PIDtq7467ruFNnZbvxlDFUdckWqt5UVlF7RdSKNDncrsecySUjtuAPIKG3LpsXuFBWSgn9sLuc6ntEfgH83SJHyyAnUM73bVzHowNpiAlWA8nMigjX0AStCBU4FihUyyOakutn11+tfM14m9dW8zbkzc9Od3MfmXvtQEUWzEcx5c0uhElCSzVHKgMjMvk34rmbQF0/eJTkRcQc0GlSN+7ngtTWVAEm4dfNTYvFQn7JZKpIq3TDw/xlPf4zd4kpbQFfezMPaI7ESEQ2dXeWRla3EMl45GGuSwcIk/AFjK6u0hdbrB/p4EL2kboU=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: postgres-secret
    type: Opaque
